### ISSUE TITLE
Incorrect path to FAQ in some of the guides

### ISSUE THREAD

**Issue by ryanjmack** [P1xt/p1xt-guides#1]
Just wanted to point out that in:

- [Computer Science and Web Development - comprehensive](https://github.com/P1xt/p1xt-guides/blob/master/cs-wd.md)
- [Get Job ready with 13 projects, 2 courses, and 10 books](https://github.com/P1xt/p1xt-guides/blob/master/job-ready.md)
- [Web Development with Computer Science Foundations - comprehensive](https://github.com/P1xt/p1xt-guides/blob/master/wd-cs.md)

the link to the FAQ is
https://github.com/P1xt/p1xt-guides/blob/master/faq

and should be:
https://github.com/P1xt/p1xt-guides/blob/master/faq.md

**Comment by P1xt** [comment]
Ahh, oops, I'll get that fixed. Thanks @ryanjmack

**Comment by P1xt** [comment]
@ryanjmack Should be all fixed now, thanks for catching that.
