### ISSUE TITLE
Components In-Depth in Vue guide is left out

### ISSUE THREAD

**Issue by Obayanju** [P1xt/p1xt-guides#101]
There isn't any reference to the components in-depth section of the docs ( https://vuejs.org/v2/guide/components-registration.html ) in the Vue topic deep dive. Only Essentials, Transitions & Animations, Reusability & Composition, Tooling, scaling up, and internals is mentioned.

**Comment by P1xt** [comment]
You can safely just continue down through the Vue docs, doing all sections.

The Vue guide is now deprecated as part of the 4.0 revamp.
