### ISSUE TITLE
Add regex app to the regex guide

### ISSUE THREAD

**Issue by P1xt** [P1xt/p1xt-guides#11]

**Comment by ksmai** [comment]
Any comments on this one? (Disclaimer: made by me)
https://regex-classroom.herokuapp.com/map

**Comment by P1xt** [comment]
@ksmai That's actually the one that's on my todo list to review and include in the guide :D

**Comment by P1xt** [comment]
@ksmai It's official, your app is added :D

**Comment by ksmai** [comment]
Thanks a lot @P1xt :smile: !!!
