### ISSUE TITLE
where is the link to the titles ?

### ISSUE THREAD

**Issue by maaqoul** [P1xt/p1xt-guides#110]
so i've entered the specialization section of the open app academy; and there is no links to the titles am a bit confused lol ? are those titles courses inside the open app academy ? or am i missing something here ?

**Comment by P1xt** [comment]
Those are sections inside the open app academy. Once you've signed up and started open app academy, you'll see them all available in the sidebar.


![App Academy Open](https://user-images.githubusercontent.com/322175/59556564-02fe7480-8f8a-11e9-81eb-982a0eb4c908.png)

**Comment by maaqoul** [comment]
thank you so much for everything, you don't even know how your guide is helping people around the world, you are such a blessing and i bet that you are a great genuine person

**Comment by P1xt** [comment]
Are you starting the App Academy Open specialization today? I'm actually starting it today myself (to brush up on Ruby/Rails) along with some friends. I'll be on twitter pretty regularly as I work through it if you want to touch base every so often while you're working at it.

**Comment by maaqoul** [comment]
to be honest i am still at the third week in cs50, but i would love to take the offer lol, what is your twitter ?

**Comment by P1xt** [comment]
@P1xt

**Comment by P1xt** [comment]
Though if you're working on CS50 - I can't overstate how much I recommend putting your nose to the grindstone and finishing CS50. 

It
is
that 
important

**Comment by maaqoul** [comment]
i
will
finish 
it
i am that determined

**Comment by P1xt** [comment]
😺
