### ISSUE TITLE
Alternatives to Learn Enough

### ISSUE THREAD

**Issue by alexgahere** [P1xt/p1xt-guides#114]
What are the alternatives to Learn Enough courses that is Text Editors and Git? You need to pay to view all the chapters.

**Comment by JoshuaPP** [comment]
This changed really recently I believe. I worked through both courses without a problem like a week ago but I am stuck now on CSS asking for payments. Just checked and same problem with JS too.

**Comment by UnmadeBed** [comment]
Yeah I just the other day finished the Just Enough...Command Line book and it too has been paywalled. Has the guide brought extra traffic to the site and tempted the author into cashing in?

**Comment by JoshuaPP** [comment]
Looks like it. Shame as the guides were really good for a basic grasp but not worth the costs in my opinion.

**Comment by P1xt** [comment]
Yeah - I'll swap it so there's nothing paywalled. It's a shame, they weren't paywalled just a couple weeks ago and they were good resources.

**Comment by P1xt** [comment]
I think I'll put App Academy in the prep section instead of as the recommended first specialization. It touches on everything in the Learn Enough series plus a lot, lot more.

**Comment by P1xt** [comment]
Refactored Tier 0 in 683a951fcddad69bd1a9fdc28efb0ec731feb811

**Comment by kauepacheco** [comment]
Probably they have noticed the traffic increasing and then decided to charge... I am waiting on the alternatives!

Thank you @P1xt for all your hard work!!!
