### ISSUE TITLE
question about 6.0001 in tier 2

### ISSUE THREAD

**Issue by samnj** [P1xt/p1xt-guides#117]
I don't understand why Introduction to Computer Science and Programming in Python (aka 6.0001) is in tier 2 when CS50 is already in tier 1. From a previous answer in a closed issue it seems that you (p1xt) think CS50 is superior, although they cover roughly the same subjects. So, what am I missing? 

Thanks a lot for the guide by the way.

**Comment by P1xt** [comment]
They cover roughly the same topics, but not entirely the same and while CS50 is superior for it's purpose where it lies in the curriculum, the 6.001/6.002 sequence provide additional practice on the common topics plus ensure coverage of all the topics that will be necessary for some of the later courses in Tiers 2-4.
