### ISSUE TITLE
Question about how to use this guide

### ISSUE THREAD

**Issue by BreezyB** [P1xt/p1xt-guides#118]
I'm still new to working with github.  How do I use this guide? I'm assuming that I clone it into my own account so that I add my progress and evidence links, but how do I keep it updated without overwriting my information. Sorry if this is obvious, I feel like I'm overthinking again.
Thanks

**Comment by vikramnr** [comment]
@BreezyB  You can fetch the latest changes. Please see the [Keeping a fork up to date](https://gist.github.com/CristinaSolana/1885435). Hope this helps :)

**Comment by BreezyB** [comment]
Thanks, it does! 
I'll go ahead and close this.
