### ISSUE TITLE
Frontend practice broken links

### ISSUE THREAD

**Issue by dianastanciu** [P1xt/p1xt-guides#120]
I noticed that in the [frontend practice section](https://github.com/P1xt/p1xt-guides/blob/master/project_ideas.md#to-practice-frontend-web-mobile-app-or-desktop-development), [this](https://webthemez.com/preview/?ballet-one-page-free-website-template/) and [this](https://webthemez.com/preview/?lookup-interior-design-bootstrap-website-template/) link doesn't display the template as expected (find picture [here](https://res.cloudinary.com/dok1sb8zt/image/upload/v1563540321/Capture.png))

**Comment by P1xt** [comment]
Interesting - I just  went and checked them myself and the issue isn't that they're not available, but rather that they are inconsistent across browsers. They just worked fine for me in Chrome, but not in Firefox. The links are good, it's just that the templates themselves provide an opportunity for cross browser improvement.

**Comment by P1xt** [comment]
I'm going to leave them for a week or two. I don't believe that I saw this issue as late as last week, so there's a chance it's a temporary issue with the platform.

**Comment by P1xt** [comment]
In the meantime - you can view the template in Firefox which doesn't appear to be affected by the issue.

**Comment by dianastanciu** [comment]
I experience the same issue in Firefox 67, Chrome 75, Opera 62, Edge 44, it's bizarre.

**Comment by P1xt** [comment]
Very odd, I checked it in Firefox 68 and it worked fine. I'll see if I can find some replacements until webthemes fixes their preview. The issue is that they switched to https for their previews but the templates (yes, it appears to be happening with many of them) are loading Google fonts over http.

**Comment by P1xt** [comment]
In the meantime, you can go to https://webthemez.com and pick any theme you like - if the preview doesn't work, just download the free version and run it locally.

**Comment by P1xt** [comment]
Ahhhh, they must have still worked in the one browser for me because I still had them cached (was doing them myself as part of a speedrun with the red pandas) so you're right, they're broken on all browsers. Will prioritize getting better links.

**Comment by P1xt** [comment]
All links should now be correct.
