### ISSUE TITLE
Why is there Calculus in Tier 1 Getting Started?

### ISSUE THREAD

**Issue by pentakillmaybe** [P1xt/p1xt-guides#123]
Hello. The Math prep. section says that I need to incrementally work through the math sections alongside the programming part. However, in tier 1, calculus is present? Is it some sort of mistake?

Also the math prep shows that I have to go through Algebra 1, Algebra 2, Trigonometry and Pre-Calculur, however, isn't geometry a prerequisite for trigonometry?

**Comment by P1xt** [comment]
It is not a mistake.

It is expected that the math prep is alongside Tier X and Tier 0, preparing for Calculus by the end of Tier 1.

The few properties of triangles necessary to understand trigonometry can be picked up while learning trig. I don't find the whole of geometry a necessary prerequisite.

**Comment by pentakillmaybe** [comment]
Can you say how much time it takes to complete those four sections of math If I spend 2h a day? I know that everybody is different in terms of learning speed but a general approximation would be nice so I that I know.

**Comment by P1xt** [comment]
Spend 2 hours a day, every day, for 2 months - then, let me know how far you got. With that much data, we can likely estimate how long it would take you personally.  Without that data, any estimate would just be some random guess with no basis in reality. I don't know you - or how much you can learn in 2 hours, or whether you'll be skipping many days, or barely paying attention, or - anything.
