### ISSUE TITLE
App Academy sign-up error message

### ISSUE THREAD

**Issue by UnmadeBed** [P1xt/p1xt-guides#124]
I've tried to sign up for the App Academy online bootcamp but I get an error message 

> /var/lang/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /var/task/node_modules/ref-napi/build/Release/binding.node)

 when doing so. I've tried both Chrome and Safari with the same result. I am based in the UK. Is it possibly open to students US only?

**Comment by P1xt** [comment]
I just tried to login with github and got an error message as well, I trust they'll get it handled.

Try putting in your email address and having them email you a login link. That just worked for me.

I know it's not US only, I have two friends from Italy working through it right now.

**Comment by UnmadeBed** [comment]
Huh, weird, I’ve tried the email path and that hasn’t worked after several attempts either. I’ll raise the issue with them and see what comes upon. Thanks.

On 25 Aug 2019, at 22:16, P1xt <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tried to login with github and got an error message as well, I trust they'll get it handled.

Try putting in your email address and having them email you a login link. That just worked for me.

I know it's not US only, I have two friends from Italy working through it right now.

**Comment by UnmadeBed** [comment]
Site appears to be working fine now. No issues on sign-up.
