### ISSUE TITLE
App Academy Open Is Intentionally Crippled & Dishonest

### ISSUE THREAD

**Issue by drstevebrulemd** [P1xt/p1xt-guides#138]
Read this thread & discussion: https://www.reddit.com/r/learnprogramming/comments/dlm40n/psa_app_academy_open_is_handicapped_designed_to/

Basically, App Academy's been going around on Reddit claiming that their program is identical to their paid one, but they have been removing modules for the free students, as well as withholding HW/project explanations that googling/stackexchange doesn't really help with. 

Asking their staff for explanations why they've been removing material we've been given dubious and evasive responses b/c they didn't want people to know that they're giving more materials to the paid students that are 'necessary' to progress through the course. Of course, they can do what they want, but they claimed multiple times, and still do that their courses are identical when they're not. Effectively, since a year ago, no one in the free version has completed the program b/c they make it **intentionally unnecessarily difficult** for Open students to get through once you reach the ruby module.

If you read the discussion above you can see what I'm talking about and a student in the paid version (which costs an astounding $30k for a 12 week curriculum - close to or as much as what a BS in CS at a college could much) will progress easily b/c of this content. 

This comment: https://www.reddit.com/r/learnprogramming/comments/dlm40n/psa_app_academy_open_is_handicapped_designed_to/f4u8z8v/

> Gyuudon 5 points 1 day ago 
> This was in person. We were given readings, videos and homework each night and a project to complete each day of class. We were given solutions and how they were solved for each project.
> However, each project always had something at the end that only a handful of people finished. Like trying to solve N-Queens the first week of class. It was just there to be a time filler if you completed the other parts fast.
> But yeah taking a quick glance at the Open AA curriculum, it doesnt to go as detailed as the curriculum that's marked private in their Github.

They claim on: https://www.reddit.com/r/learnprogramming/comments/9oq32j/app_academy_is_making_its_entire_fullstack/

and https://open.appacademy.io that the only differences are 'paired programming,' 'live mentoring,' 'daily live lectures,' 'career advisement', etc. NOT withholding materials to progress through the course. It's fair and reasonable to offer certain services, mentoring, tutoring, live lectures, etc. to paid students - but it's not right that they remove stuff from the free to make it harder for them to proceed. If that's what they want to do, then they certainly shouldn't be claiming the programs are identical which is a point they've made numerous times on their reddit thread, website, and slack chat. 

> kpatel737
> It's the same curriculum! We have 2 paid options. The mentorship option is a $29.99/month subscription to a Slack channel (i.e. chat room) with one or more App Academy instructional staff 60 hours a week (M-F 6AM-6PM). If it sounds like an insanely good deal, that's because it is :) The placement based plan is the same experience as our full-time, in-person course, but online. **You get instructional support, live q&a, pair programming, career support, etc.** On this option, we don't get paid until you find a job, so we keep fighting until you do. In that case, it's 17% of your salary for two years, **up to $30k total.**

> [–]kpatel737[S] 15 points 1 year ago 
> Lol **idk about catch**, but we are hoping that folks recognize the quality of our curriculum **and tell their friends about it. If **it helps increase interest in our paid services** (online or in-person bootcamps or other classes), that would be awesome**. If not, I'll still be happy we did it because of how much I wished something like this existed back when I was learning how to code.

> [–]EinsteinTheory 2 points 12 months ago 
> Im kind of confuse**, If you think it takes 2,000 hours. How is it possible that your boot-camp only takes 12 weeks to complete?**

> [–]kpatel737[S] 4 points 12 months ago 
**> Because we provide a lot of external help :) The instructional support and accountability mechanisms we have in place increases your velocity significantly.**

> kpatel737[S] 5 points 1 year ago* 
Yep it's from our paid service. We just launched the free curriculum, so we haven't had time to place anybody from that yet unfortunately. **That said, the curriculum on http://open.appacademy.io is the same exact one we use in our paid class.**

So why are they claiming the programs are identical, removing content, and making it harder for free students by withholding content they're supposed to get? 

The only reason can possibly be because they're just promoting themselves to make themselves look better unlike real FOSS programs. 

For that reason, I would suggest TOP, FCC, etc. instead that are unequivocally open, designed for students to succeed, and don't penalize students that can't afford their $30k fee.

If App Academy, at least, honestly mentioned that students in their 'free' curriculum are at a deliberate disadvantage than the paid ones that would be fair and reasonable  but they're trying to make the claim that 'we're free and altruisitc' bandwagon when all they're just trying to do is encourage people to get unnecessarily stuck, and go for their $30k program... I find that behavior dishonest and distasteful to say the least.

> Here's what someone in slack said: "I've had multiple software engineers look at some of these solutions and they're far beyond the capabilities of a beginner dev. They also tend to have zero comments which makes it pretty hard to contextualize why certain decisions were made in the code. It's not an impossible task to figure out how to progress through in spite of these shortcomings, but it does make the journey longer than it needs to be. This course would borderline absolute perfection if it had a bit more to offer students in the form of video walkthroughs. If not for every single project, at the very least for every few major projects."
> " I’m sure you would agree it wouldn’t have taken you 2 months to get through the Ruby section had we been able to watch a walkthrough every once in a while to pull all of the concepts together. I’m 1.5 months into the Ruby section myself and would move a lot quicker if I could digest an occasional deep dive. The fact that the main course does have these walkthroughs underscores how valuable of a tool they can be in any learning arsenal, especially auditory and visual learners."
> We all already google, and use stackexchange. The problem is that solutions are way beyond the scope of the material taught in the later modules (typically around ruby). It's like being taught 2 + 2 = 4 and then being told to do 10 * 5.
> So there's inconsistencies like that and they omitted the explanations which are supposed to be part of the curriculum but only the paid students get (which they never said would be the case), and make learning the material more straightforward. At no point during the course do they say that you have to rely strongly on googling, or stackexchange, etc. which is things we implicitly already do.
> While the Open course in its current form is not impossible to complete, in any way, there are gaps in material that need to be filled elsewhere. So it should be made clear that this is expected, and not some kind of ding against a students’ ability to use the course materials. The A* pathfinding project, for instance, is extremely difficult to figure out without supplementary material.

> StockDC2
> Not that I'm siding with App Academy but wouldn't having to seek answers on Reddit and SO be beneficial in the long run? Very rarely is anything handed to you on a silver plate and if it is, it really gives you a narrow view on how a resource is used.
> As someone that has gone through tutorial hell, having someone hold your hand makes it very easy to think that you understand something. As soon as they let go, you realize that you don't know anything.

> salqueue
> You bring up a fair point. If we follow that logic though, then App Academy shouldn’t offer these walkthrough videos to their paid students for the exact same reason. Since they decided that the tradeoff to offer this extra resource is worth it for their paid students, there’s no pedagogical reason to hold it back for free students.

**Comment by P1xt** [comment]
I am not removing App Academy from my guide. Yes, it's tough to do the free option solo - but it's worth the effort.

I will not be putting FCC in my guide.

**Comment by drstevebrulemd** [comment]
The point is no one has finished the free version because they withhold critical course materials. You have to pay extra to get them. I thought you only used materials that are entirely free? App Academy's is not.

**Comment by P1xt** [comment]
I disagree that those materials are necessary. Yes, it would be nice if they were available, but not having them does not prevent a motivated learner from gaining a lot from the materials that are provided.

I include TheOdinProject as well, as a potential specialization. I'm still not putting FreeCodeCamp anywhere on my guide.

**Comment by drstevebrulemd** [comment]
> I disagree that those materials are necessary. Yes, it would be nice if they were available, but not having them does not prevent a motivated learner from gaining a lot from the materials that are provided.
> 
> I include TheOdinProject as well, as a potential specialization. I'm still not putting FreeCodeCamp anywhere on my guide.

That's because you haven't done the course then. The majority of students who have been doing the course full time are getting stuck in later modules because they withhold information.

> from gaining a lot from the materials that are provided.

Nope - considering that there's been thousands of people enrolled and the program's been around for about a year now, there's been no success stories. The ones that get through already have a BS in CS or did a prior bootcamp.

99% of people have not gotten through. It has nothing to do with motivation, or lack of persistence, etc.  In the real world, no one's completing the program b/c of the omissions they deliberately make. 

Just letting you know that most people are going to run into issues because of how they advertised the program.

**Comment by P1xt** [comment]
Please feel free to continue to voice your opinion.

Know, however, that I'll most likely remove this issue because it is beginning to seem an unwarranted bash on App Academy that's potentially driven by some competitor and made in poor faith.

You have near zero history on Github, aren't even using this guide, and are spouting wild allegations that a program App Academy themselves say will be tough and take longer to do on your own hasn't been completed by anyone when it's barely been available for a year. 

Yet, you also tout FreeCodeCamp, which has barely been finished by anyone, has ridiculously poor content that requires far more reference to 'outside resources', and results in far less learning. I mean, seriously, FreeCodeCamp has been out for 5 years, used by hundreds of thousands if not millions, and in all that time only a few thousand have ever finished it, and no one finished it using it as their only resource. There are issues I opened on FreeCodeCamp a year and a half ago about lessons that were broken to the point that they could not be completed as instructed - that are still open, or were closed with no resolution because they were open too long with no resolution.

If you are experiencing an actual issue completing a specific section of App Academy, feel free to ask. My DMs on Twitter are open and I help people get unstuck all the time.

But, don't come on my repo spewing a bunch of gloom and doom horror stories about a resource I've personally used and know to be of substantial quality and which I know others (who I am in personal, consistent, contact with) are learning by leaps and bounds with.

A bunch of made up statistics and sweeping generalizations about 'most' and 'many' isn't helping anyone. And, it's not relevant to my repo. If you want to throw a tantrum at App Academy, go throw it in their slack. If you're actually working through my guide and are stuck on something, feel free to send me an 'I'm stuck, can you help me understand X' on Twitter.
