### ISSUE TITLE
Full Stack Open will be available in 2020

### ISSUE THREAD

**Issue by srithasriram30** [P1xt/p1xt-guides#140]
I just checked out the Full Stack Open page, and according to their [FAQ](https://fullstackopen.com/en/faq/), there will be a new version of the course in 2020. It will start 15/3/2020.

**Comment by P1xt** [comment]
Thanks!

Yes, I've been watching for them to update to see if I should remove this or just note to start up once the 2020 version kicks off. It really is a fantastic course.

**Comment by hoskad** [comment]
Do you still think we should complete the app academy specialization first? My only gripe is all the time spent on ruby/rails. Love your guides btw! I am currently using it to supplement my curriculum at school.

**Comment by P1xt** [comment]
I still wholeheartedly endorse doing App Academy. The point isn't that you're learning Ruby/Rails, it's that you're learning good software development processes that will transition to any other language or framework.

**Comment by hoskad** [comment]
Fair enough! I'm sold. Thank you for the response and amazing guide :)

**Comment by P1xt** [comment]
Updated to the 2020 version
