### ISSUE TITLE
All Courses in Stanford Online Lagunita ends on March 26, 2020  

### ISSUE THREAD

**Issue by garymdurante** [P1xt/p1xt-guides#142]
https://lagunita.stanford.edu/courses

> This course ends at 12 noon Pacific Time on March 26, 2020. If a Statement of Accomplishment is available for this course, it will be available for download until March 31, 2020.

**Comment by P1xt** [comment]
Thanks for the heads up. I've not yet seen an announcement from them about how they are transitioning those courses. If I've not seen something by mid-March, I'll start replacing them with alternative content.

**Comment by garymdurante** [comment]
Stanford launches courses on edx
https://vptl.stanford.edu/news-events/news/stanford-online-launches-courses-edx

It's now paywalled.

**Comment by P1xt** [comment]
Well, drat.

Thankfully, I'm not using many courses from there. Mainly I'll have to find an alternative for databases.

**Comment by vasilygrz** [comment]
I've written [about this issue on OSSU](https://github.com/ossu/computer-science/issues/645#issuecomment-586891832), focusing and providing information about the Introduction to Databases course.

**Comment by P1xt** [comment]
Updated with alternate resources.
