### ISSUE TITLE
About courses price and timeline ?

### ISSUE THREAD

**Issue by mgamal92** [P1xt/p1xt-guides#144]
Are all courses included in this path free ? and another question what time expected to finish the roadmap ?

**Comment by DaveMoran** [comment]
@mgamal92 the guides here are all self paced. Some of them do have their own timelines, like the [Full Stack Open](https://fullstackopen.com/en/). but the guides are kept pretty up to date with these things.

As for pricing, you should be able to do everything here for free, but if you do find something behind a paywall during your journey just raise an issue and the community should be able to find an alternative resource
