### ISSUE TITLE
About reading the docs ?

### ISSUE THREAD

**Issue by mgamal92** [P1xt/p1xt-guides#146]
I saw in reading list something like reading Angular, Vue, React docs . Why? and before them I saw you suggest to read Jest docs also . Can you explain for me why you recommended these docs in this order ?

**Comment by P1xt** [comment]
Why? So that you learn about them completely. Why this order? Because, that particular order makes sense as a flow within your beginner to advanced journey.

**Comment by mgamal92** [comment]
many thanks for your effort :)
