### ISSUE TITLE
stanford courses

### ISSUE THREAD

**Issue by Lithial** [P1xt/p1xt-guides#151]
Looks like the date for the stanford courses has finally come and gone. I think they moved a bunch to edx now. 

ps also might be time to look at machine learning resources now? looks like theres some interesting new stuff including a cs50 course on it

**Comment by P1xt** [comment]
I already swapped out the stanford courses for other resources.

**Comment by P1xt** [comment]
Making a note about the AI course. It looks to be starting at the end of this month, I'll want to review it before deciding where/if to add it:

https://www.edx.org/course/cs50s-introduction-to-artificial-intelligence-with-python
