### ISSUE TITLE
Tier X - Math Prep Requirements

### ISSUE THREAD

**Issue by Ahmed-Magdy-S** [P1xt/p1xt-guides#154]
thank you for your guide,
my question is: what are **Requirements** needed to take  **'Tier X - Math Prep'** ?
it needs prior knowledge of some math level or anything like that ?

**Comment by RoamingBlue** [comment]
If you had any sort of math up through elementary and middle school, you should be fine to start algebra.

**Comment by Ahmed-Magdy-S** [comment]
> If you had any sort of math up through elementary and middle school, you should be fine to start algebra.

@RoamingBlue that's a problem, I didn't know if I had enough knowledge, I didn't study math for more than 7 years ago , it's a very long time , so what should I do ?

**Comment by RoamingBlue** [comment]
Try starting with Algebra, if it's too difficult, back up to an easier course.

**Comment by RoamingBlue** [comment]
If algebra is too difficult, start with [pre-algebra](https://www.khanacademy.org/math/pre-algebra)

**Comment by Ahmed-Magdy-S** [comment]
@RoamingBlue Okay, Thank you very much
