### ISSUE TITLE
Which to follow for Data Science?

### ISSUE THREAD

**Issue by AlvinNg89** [P1xt/p1xt-guides#157]
Hi p1xt,

First off, a big thank you for the wonderful guide. It really takes a lot of effort and i appreciate it. I'm here because I'm interested in learning Data Science but I realize it only comes in at Tier 2. That also means I will be going through web development first (Tier 0) which is not my main interest. How would you recommend i use your guide for my purpose? Should i still go through Tier X - 0 - 1 then 2? 

I also notice that there is a deprecated guide for Data Science. Will that be more suitable?

Thanks in advance!

**Comment by P1xt** [comment]
That really depends on where you are now from a skills perspective.

In general though, if you want to skip 'the easy basic stuff' and get on with it, you can safely skip everything up to CS50. Start with CS50 and continue from there.
