### ISSUE TITLE
App Academy takes too much time

### ISSUE THREAD

**Issue by shivendrarox** [P1xt/p1xt-guides#158]
Hi!
Thanks for this awsome guide. I was doing app academy, and now i have reached the 'Ruby' secton and was doing the memory puzzle. At the beginning things were fast but now it has become too lengthy. I am able to keep up with difficulty but all this is taking too much time and there is a lot more left. I am in a bit of hurry (looking for a job..etc). what should i do? do tier 1 and begin with cs50, or should i continue with app academy. we can do app academy as a specilalisation in any of the tiers, right?

**Comment by P1xt** [comment]
App Academy does take time. However, you are learning more in that time than you would devoting that time elsewhere.

That said, your journey is your journey. Make the choices that best suit your goals.

If you don't like my recommendation, carve your own path and take responsibility for your choices.

I will say that finishing one thing is typically more effective than starting 10.
