### ISSUE TITLE
Learn Enough Series is under paywall now

### ISSUE THREAD

**Issue by regadius** [P1xt/p1xt-guides#159]
Almost all Learn Enough Series tutorials (except for Command Line) are now under paywall. Only a couple chapters are available for free. I do not have an alternative to suggest yet, just want to let you know so you could decide on what next action to take regarding the resource recommendation.

https://github.com/P1xt/p1xt-guides/blob/master/specializations/the_odin_project.md
https://www.learnenough.com/ruby-tutorial/hello_world
https://www.learnenough.com/action-cable-tutorial

**Comment by P1xt** [comment]
Drat, I removed all the other Learn Enough resources last year and somehow missed the Odin Project Specialization. I'll look into replacing them there. Thanks for the catch!

**Comment by P1xt** [comment]
I think for the moment, I'm going to remove the readings from the Odin Project specialization. Most of the potential resources to replace the Learn Enough series wouldn't add much value beyond what completing the Odin Project itself. This also looks like a good opportunity to add in the JavaScript track of the Odin Project as a separate specialization so I might add that in as well.
