### ISSUE TITLE
Why my issue closed?

### ISSUE THREAD

**Issue by ghost** [P1xt/p1xt-guides#161]
Why close my issue before I had a chance to reply? You actually said that not to bother with Ruby and I clearly remember that was your reply to someone's question. I don't have a memory issue. Don't be arrogant saying "You never saw me post on the FCC forums or anywhere else not to bother with learning Ruby" I would prove it but you have decided to remove all your posts on FCC forums. Because you have habit of doing that when people try to prove you're wrong sometimes.

You know what I'll go and study elsewhere. This is not a miracle curriculum. You're always right everyone else is wrong, yeah? I'd rather not take advice from a hypocrite!!!! Now go on close this issue as well.

**Comment by P1xt** [comment]
1. You can still comment on closed issues, there's no need to create a new one.
2. I'm frequently wrong, and admit it when I am.
3. I never posted that on the FCC forums. Other's posted to not bother learning Ruby. I've never believed that, and thus, never would have posted it.

**Comment by P1xt** [comment]
No curriculum is a miracle. Nothing I propose, nor OSSU, nor CS50, nor App Academy, nor any other resource anywhere is the miracle. The miracle is the effort you put into learning. You make your own miracle by studying and learning and getting good at whatever you prioritize - all any of the rest of us do is try to illuminate a path that might be helpful.

Stop calling me names. That's a shitty thing to do in someone else's repo.
