### ISSUE TITLE
Include 'The Missing Semester of Your CS Education'?

### ISSUE THREAD

**Issue by MarcinFortuna** [P1xt/p1xt-guides#171]
Hello,

Have you considered adding [The Missing Semester of Your CS Education](https://missing.csail.mit.edu/) to the guide? It's an awesome source for acquiring basic proficiency with CS tools and it's free!

**Comment by P1xt** [comment]
I have considered it, but it's relatively new and I want to make sure it's going to stick around a while before I add it. If MIT had put it on their OCW site, I would have added it by now but sometimes their csail stuff gets pushed behind a wall you can only access with a MIT login.
