### ISSUE TITLE
Can I complete this guide in 5 years?

### ISSUE THREAD

**Issue by elshvfi** [P1xt/p1xt-guides#179]
I’m a medical student who wants to develop apps/websites, and get into AI/Machine learning in the future. In my case, should I complete the whole guide or is there a specific tier I should stop at? I’ll be dedicating 2 hours of my time everyday working through this guide and hope to complete it in 5 years.

**Comment by P1xt** [comment]
I honestly can't say with any certainty or integrity how long it will take you as I have no knowledge or control over your study habits or persistence.

**Comment by elshvfi** [comment]
Okay, for someone who wants to learn how to develop apps/websites and
AI/Machine learning programs, would this guide be suitable? Because I’m
confused on what the difference is between Computer Science vs Software
Engineer.

**Comment by P1xt** [comment]
My recommendation would be to complete App Academy Open and CS50 to build a solid foundation and then assess where you are and determine the most logical next steps for you personally. Once you have a bit of a foundation, it will be much easier for you to gauge how quickly you progress and where your interests are.

**Comment by elshvfi** [comment]
Say for example, I completed tier x, tier 0, and tier 1 to establish a good
foundation. Can I go on to complete all the other specializations without
having to go through the Computer Science courses/readings or will they
help me in completing those specializations? I’m just confused on when I
complete this guide, will I know how to be a data scientist or an overall
developer/programmer? (I’m sorry for the questions, I really want to
complete your guide because it looks phenomenal but I’m just confused on
complementing it with my medical career.)
