### ISSUE TITLE
Add advice about helping others to the FAQ.

### ISSUE THREAD

**Issue by P1xt** [P1xt/p1xt-guides#18]
from eliotn in the Chingu Cohorts

> p1xt Maybe you should include helping someone in person on the things you should do list (but it might not be practical for everyone). Just helped someone today who wanted to web scrape by introducing them to selenium.

**Comment by Obayanju** [comment]
GOLD

**Comment by P1xt** [comment]
closed with 6e65921d82e99615bd31d631205073eb8b8ed182
