### ISSUE TITLE
Are the OCW Courses Complete?

### ISSUE THREAD

**Issue by eldanieldev** [P1xt/p1xt-guides#180]
Are the the MIT OCW course listed in tiers 2 onward complete, or even complete enough? I looked over most of them and noticed Mathematics for Computer Science is not found and others lack lecture videos. 

Is the content complete enough in these courses to succeed in them?

**Comment by P1xt** [comment]
I fixed the link for Mathematics for Computer Science and then spot checked the rest of them to make sure this year's mitocw revamp didn't break any of the others.

The vast majority of the mitocw courses I chose to include actually have lecture videos. Notably, the computation structures course doesn't, but it's quite well self-contained and by Tier 4, you should be well prepared to study lecture notes and texts as a primary learning method when videos aren't available.
