### ISSUE TITLE
Tier 0 mentions Full Stack Online courses but no links

### ISSUE THREAD

**Issue by msemko** [P1xt/p1xt-guides#183]
I googled Full Stack Online and could not find these courses? Is this outdated? Are there links?

![image](https://user-images.githubusercontent.com/90331855/168178475-55369d66-5a45-4f75-81e9-92720e7bc8c0.png)

**Comment by DaveMoran** [comment]
Hey @msemko , those would be the titles for the courses but it looks like they've made some curriculum updates. Just follow the ones that are listed when you log in to the App Academy Open link

**Comment by eldanieldev** [comment]
[This](https://open.appacademy.io/login) is the link to find the old Ruby curriculum.
