### ISSUE TITLE
Some course links are not specified or unavailable 

### ISSUE THREAD

**Issue by Sazid99246** [P1xt/p1xt-guides#192]
Hello there. I have found that the courses listed below, which are from cognitive class ai are unavailable. And the courses from MongoDB unicersity are not specified, like when I go to the mongodb university, I am seeing all the courses from the mongodb. Please correct all the links. 

 []()![Screenshot_2023-01-23-08-25-23-673_com.github.android.jpg](https://user-images.githubusercontent.com/96985876/213957393-a3fc92cb-8f53-4b42-bee8-193ca0e3d824.jpg)

![Screenshot_2023-01-23-08-25-06-407_com.github.android.jpg](https://user-images.githubusercontent.com/96985876/213957394-c7974282-5196-4064-b3d6-4003252c17b0.jpg)

**Comment by P1xt** [comment]
It may take me about a week because my week is beyond busy this week, but I'll look into this.
