### ISSUE TITLE
Update 6.006 to 2020

### ISSUE THREAD

**Issue by samnj** [P1xt/p1xt-guides#194]
Unless there's a particular reason to stick to the old one, the 2020 Introduction to Algorithms could be the better option. Better video/audio quality and part of it was recorded during covid so it was intended for remote consumption.

https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020

**Comment by P1xt** [comment]
I ensured this was updated with the v5 revamp.
The v5 revamp went live with commit 352bfafcaa81f07186c96297e13e03de0f818fad
