### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by ChouyahDamyen** [P1xt/p1xt-guides#195]
Hello, I would like to know if we should use the v1 or v2 of app open Academy? and I also wanted to know if your path for the development of video games was still current? 
Thanks to you

**Comment by P1xt** [comment]
I'd probably go with V2 -  both are good, but I expect they'll sunset V1 at some point this year and move that curriculum into the newer app.

Yeah, the gamedev specialization is still current.

**Comment by ChouyahDamyen** [comment]
Thx you for your work man
