### ISSUE TITLE
Broken links from the curriculum

### ISSUE THREAD

**Issue by kuntsarpyalcin** [P1xt/p1xt-guides#198]
Hello, I recently found this wonderful curriculum but I found that there are some broken links and they need to be corrected or replaced with different courses:

Tier 1 - This one redirects to a paid "Nanodegree": Software Debugging (https://www.udacity.com/course/software-debugging--cs259). And this one is completely broken: Software Testing (https://www.udacity.com/course/software-testing--cs258)
All tiers - All Google Kick Start, Google Jam and Facebook Hacker Cup links are completely broken.

**Comment by Aftarto** [comment]
Yeah, some of the links appear to be broken. I hope P1xt takes a look at this.

**Comment by P1xt** [comment]
Yeah, I'm aware that some of the practice links went dead when Google cancelled their coding competitions and took the site down last month. I'm looking into alternatives.

If you have actually done all the curriculum up to a point where there's a dead link and are legitimately hindered and cannot progress, let me know where you are, what you've completed, and where you're stuck and I'll prioritize getting that link fixed or replaced.

**Comment by kuntsarpyalcin** [comment]
Thank you very much for your answer! Actually, I am at the beginning of the curriculum and I just encountered those broken links when I became curious to check out the links in the curriculum. Definitely, if I become stuck because of a broken link in future, I will inform you. Thank you very much again for all your efforts to provide and maintain this wonderful curriculum!
