### ISSUE TITLE
Job Ready and Computer Science and Web Development 

### ISSUE THREAD

**Issue by IbrahimButt** [P1xt/p1xt-guides#2]
I want to be a software developer/engineer, but I also want a job as a junior web developer for the time being, while I educate myself to become a software engineer.

Should I begin with Computer Science and Web Development (CSWB) and apply for jobs as a junior web developer once I'm finished with Tier 1, or, start and finish Job Ready, apply for jobs and then CSWB while working/looking? If it is the latter, should resources/projects/courses be followed in a different order?

My reason for asking is CSWB involves HTML and CSS too, but there is a difference in some resources/projects/courses and some are in Tier 2 instead.

**Comment by P1xt** [comment]
My typical recommendation is go CSWB and apply for jobs as a junior web developer once you are finished with Tier 2 (not Tier 1) while you finish the rest.

In the final analysis though, what it really comes down to is this: You're an adult, and only you are responsible for the decisions you make regarding your educational goals, your "patience" level, and your career. Make the choice that you personally can live with.

I can "recommend" a path, but in the end, you are the one who has to develop the determination, dedication and perseverance to follow it, so it makes more sense if the path chosen was chosen by you - you're the one who has to put in the hard work of following it and it's a lot easier to do something you decided to do than something someone else decided you should do.

**Comment by IbrahimButt** [comment]
Ultimately I want to get into Machine Learning and Ai and this sets out a path for me, so I'm happy with it. I'll be making sure to do the projects in Python too.

Thank you.
