### ISSUE TITLE
Skipping some courses

### ISSUE THREAD

**Issue by DiamondMonster090** [P1xt/p1xt-guides#204]
Hello. Before starting this guide, I had already finished CS50x, so do I need to skip straight to after CS50 in section 1 (and skip App Academy)? or should I do App Academy and skip some parts? should I do something else?

Also, I want to thank you for this amazing guide. I just started it, but it looks great!

**Comment by P1xt** [comment]
I'd still do either App Academy or Full Stack Online (they are both really great at getting you a lot of practice hands on coding.)

**Comment by DiamondMonster090** [comment]
You said in the FAQ that full stack online is starting at a more advanced level, so should I do it instead? from what I saw in app academy it is (at least the beginning) very easy and simple.
Thank you!

**Comment by P1xt** [comment]
App Academy "starts off" easier - by midway through, it's as tough as Full Stack Online. And, Full Stack Online is updated more frequently.

My advice: try a bit of both (30 minutes max each) then pick the one YOU like better and commit to that one, finish it all the way to the end, even if it gets hard - all the best learning, the stuff that will skyrocket your ability, is in the last 25%. So whatever you do - FINISH IT.

**Comment by DiamondMonster090** [comment]
Ok. Thank you!
