### ISSUE TITLE
Split readings into references (docs) and regular readings?

### ISSUE THREAD

**Issue by WildGenius** [P1xt/p1xt-guides#211]
I presume you don't intend for someone to, e.g., read MDN top to bottom, but do recommend reading Eloquent JavaScript in full. In fact, it seems like readings are mostly docs, so possibly rename the tables to "Documentation" and factor out smaller tables for "Further/recommended reading"?

**Comment by P1xt** [comment]
> I presume you don't intend for someone to, e.g., read MDN top to bottom

I'm not entirely sure why you presume this when throughout the whole document I heavily stress the importance of learning to "read the docs"

It's an important skill ... that you can develop for free ... by reading the docs.

**Comment by P1xt** [comment]
I'm not going to argue the point I've already made with you.

The docs are where I want them and listed as I want them.

**Comment by P1xt** [comment]
Perhaps, if you have a question, you might ... ask the question ... instead of continually telling me to do things I've made it clear I have no intention of doing.

**Comment by P1xt** [comment]
> Leverage the reading material listed for this tier while completing the projects. It covers the materials from the courses in much greater depth and will help a lot. You should be familiar with both reading it and using it as a reference when you have questions by the end of the tier.

**Comment by P1xt** [comment]
The only communication barrier seems to be that you cannot fathom being told no.
