### ISSUE TITLE
Repeated course

### ISSUE THREAD

**Issue by jaroldwong** [P1xt/p1xt-guides#25]
In JavaScript Job Ready 2.0, the course Programming for the Web with JavaScript appears in both Tier 1 and Tier 2.

**Comment by P1xt** [comment]
Good catch, I'm still thinking on what I want to do with that line in Tier 2, my inclination is to leave the MongoDB University course but I haven't quite landed on how to word it. I should take the Programming for the Web course off that line though while I settle on what exactly to put there.
