### ISSUE TITLE
For any requests for new guides please post here.

### ISSUE THREAD

**Issue by P1xt** [P1xt/p1xt-guides#3]
Current ideas I'm thinking about for new guides include:

- [x] Native Android Development (Complete 5/2017)
- [ ] Android development with Angular 4 / Ionic
- [x] Python Programming (Complete 9/2017)
- [x] Data Science (Complete 9/2017)
- [x] Revamp original Job Ready guide (Complete 9/2017)
- [ ] Mastering Linux
- [ ] Testing Web Applications
- [ ] Revamp and organize productive break section of FAQ

If you have any other ideas you'd like me to consider (or want to vote vigorously for one of the ones I'm already considering) please discuss it here.

**Comment by Obayanju** [comment]
A guide to mastering Linux would be great.

**Comment by P1xt** [comment]
That's a good idea @Obayanju - there's a lot of power available to you at the command line, if you only know how to tap into it.

Adding this to the list

**Comment by jdmedlock** [comment]
A guide for testing and best practices when designing and implementing tests.

**Comment by P1xt** [comment]
@jdmedlock added it to the list, I think that might make a great "addon" mini-guide that could be dropped in as an extra Tier on any of the three that cover Web Development.

**Comment by fiftyfivebells** [comment]
Not a suggestion for a new guide, but maybe you could add an additional section to the guides or the "productive break" area with ideas for projects with a focus on something other than web development. 

Particularly for the comp-sci focused guide, it could be interesting to build something different. I know there's an Android app in there, and a bunch of algorithmic type projects, but other things could be fun!

**Comment by P1xt** [comment]
I like that idea @fiftyfivebells - perhaps I'll pull the "productive break" section out into it's own page and give it a bit more structure, with separate sections for various activities: projects, books, courses, exercises, etc.

**Comment by shreyas23sk** [comment]
Well, looking forward to the android development guide. I know some android development, but I am not a master. 
Also, Artificial Intelligence is a great one to look up to.
By the way, what would you include in the Python guide? I mean, what would we be building?

**Comment by P1xt** [comment]
The python guide is going to take some thought. Ideally, I'd like to go with rigorous foundations and then branch out a bit into a taste of a variety of applications - a bit of web-dev, algorithms, machine learning, maybe even some pygame.

**Comment by shreyas23sk** [comment]
The android guide looks awesome,  I know some android, and my hands are itching to jump in tier 1 and tier 2 right away.
But, since I have already committed to the CSWD guide.

So, looking forward to the productive break list, if it gets materialized.

**Comment by P1xt** [comment]
@shreyas23sk Oh, it will, there's already an abbreviated version of it in the FAQ, it'll just need to be moved into it's own file and expanded on.

**Comment by P1xt** [comment]
I've created a poll, if anyone would like to "vote up" anything of particular interest.

[Vote here](http://www.poll-maker.com/poll1078498x337e42c4-45)

**Comment by AbhayKV04** [comment]
OK now I'm confused. I just started CSWD guide (currently on YDKJS: Scope & Closure) and I want to finish it, but the Android guide you just put up is also tempting since I also want to do that. So it's CSWD vs Android. Should I keep on doing the CSWD one or should I finish the Android one and then get back to CSWD? Or could both guides be blended together somehow? Help!
P.S. You may want to review the syntax of some your Android projects markdowns.

**Comment by P1xt** [comment]
@AbhayKV04 
I'll take a look at the syntax in the Android project specs. Yep, looking at them I should have done a bit of a cleanup on them.

Of the two, if I had to pick, I'd do the CSWD guide, it has the most universal application and will benefit you no matter what sort of development you eventually intend to pursue. The android one sure would be fun though :D

**Comment by benjaminthedev** [comment]
What about iOS / swift dev?  I personally would love to see that!

**Comment by P1xt** [comment]
I've long considered the question of whether to include ios in the guides. In the end, if I do ever end up writing an ios guide it will likely be one of the very last - my reasoning being that I prefer to focus on guides where there's no financial barrier to learning and to develop for ios devices you actually have to have a Mac. So guides like ios (must buy a Mac) or IOT guides where there's a hardware investment (rasp pi or arduino) will likely come much later than guides like "learn to test" or python, data science, etc.

It's not that I wouldn't have a blast writing them, because I'm quite interested in the material, I just don't want to put together guides where step one is "now first, go buy x 'cause you can't do this without dropping some cash".

**Comment by heggy231** [comment]
I was recommended by LinkedIn employee to focus learning about mobile app (ios app).  Could we add this to the list?

**Comment by MikailSeremet** [comment]
Can we have an updated trello board for courses?

**Comment by P1xt** [comment]
@MikailSeremet Sorry, I never maintained the trello boards and prefer having the guides in github markdown where you can just check off items as you finish them.

**Comment by rangelke** [comment]
@P1xt @MikailSeremet I also prefer the markdown checkbox on github for it. Trello is awesome, but I thouht it was a bit overkill for a guide.

**Comment by P1xt** [comment]
@rangelke @MikailSeremet In general, I love trello, I use it all the time. But, github just makes version control so easy, I can update the repo and everyone can merge the changes right into their fork and be consistently assured that they have the most updated version. With trello boards, everyone would have to go in and update their private board manually, which just seems messy to me.

**Comment by AliMahmoud7** [comment]
A Guide to Cyber Security and Ethical Hacking will be valuable :closed_lock_with_key:

**Comment by AbhayKV04** [comment]
Why should one follow your guide instead of OSS's? Just curious.

**Comment by AhmedA-del** [comment]
**actually all these guides look awesome to me**
how are you doing by the way didn't hear from you since you left FCC ?

**Comment by P1xt** [comment]
Hey there @AhmedA-del I've been doing great, getting a lot more work done, wrote a couple more guides, and have a lot more time to devote to the Chingu cohorts .... best decision I ever made.

How are you doing?

**Comment by P1xt** [comment]
@AbhayKV04 You alone are responsible for your decisions and your life. You will have to make the choice yourself, based on what you want to accomplish.

**Comment by AbhayKV04** [comment]
@P1xt I know that :) I was just curious on how you curate your list from other guides and resources, what to keep, what to discard, etc.

**Comment by P1xt** [comment]
@AbhayKV04 Usually I get an idea about what the main purpose of the guide is, what a person should be able to do once they've completed it. Then, I do a bit of a "deep dive" into the material myself, getting a sense for which resources are not just outstanding in their own right, but also work within the overall narrative of the guide I want to put together. It's not really a matter of picking the best book for X and the best course for Y so much as it's about weaving together resources that build upon each other in a "whole is greater than the sum of the parts" sort of way.

**Comment by northern11** [comment]
+1 for DevOps. How about a Database guide? Or this could be a break off section that supports any projects that are part of the current guides.

**Comment by MikailSeremet** [comment]
+1 for devops or especially on docker guide would be nice!

**Comment by P1xt** [comment]
I think devops including docker would be a decent sub-guide, I'm considering it, python, or data science as the next guide, but being slow about it so as not to distract people from the cs guide at the moment.

**Comment by HosTilezZz** [comment]
first I'd like to tell you that i swear by your guides, I've shared it with everyone i know, we just can't thank you enough for it.
i just have a small suggestions, i think you should add Kyle Simpson's "[Functional Light JS](https://github.com/getify/Functional-Light-JS)", i found it while trying to wrap my head around javascript allonge, it was a bit hard for me to understand this book, but after reading kyle's book it became a lot easier and it made a lot more sense.

**Comment by alanthony333** [comment]
@HosTilezZz Thanks for the tip. It might come in handy for a newbie like me. :)

**Comment by P1xt** [comment]
@HosTilezZz I get what you're saying about Kyle's Functional Lite book, it's awesome, but unfortunately it's not as comprehensive as Allonge. Adding it would start the guides down the slippery slope of "add easier busywork to make the 'real' resources easier" - and I just can't/won't do that, it would bloat the guides too much, and they're already pretty big as they are. Sure, Allonge's tough, but it's not impossible, especially if you've already got YDKJS and CS50 under your belt.

For literally every single item on the guides, I could add 2-4 easier resources to build up to it, but that would be disrespectful to everyone following the guides. First, disrespectful of their time as it would at least double the length of the guides. But, more importantly, disrespectful of the trust I have that a determined learner will study, and learn from the current resources and counter to one of the secondary goals of the guides - fostering the confidence that comes from knowing you don't need baby-steps, you can jump in and tackle real honest-to-goodness professional level resources.

**Comment by HTMLNoob** [comment]
Would Flexbox be useful to add to the web development guides or should it stick to Bootstrap?

**Comment by P1xt** [comment]
Flexbox is just CSS - some extra CSS you can sent just like you can set color or border or font. There's no reason for it to be added. If you need more CSS instruction, use the Shay Howe courses listed in the FAQ and the longer guides, then just hit MDN and lookup Flexbox like you would any other CSS you want to use.

**Comment by HTMLNoob** [comment]
Could it be reasonable to add a Node.js tutorial or good Node.js resources to the FAQ?

**Comment by P1xt** [comment]
@HTMLNoob It's my hope that if someone has followed the guide, they will be able to read the node, express, and mongo documentation by the time they need them.

**Comment by LordKrishna91** [comment]
The web development guides are awesome
 Thanks for the guides 😇

will there be guides for ruby  & rails development?
it would be great if some advanced ruby material was added to the guides.
Thanks in advance.

**Comment by P1xt** [comment]
@LordKrishna91 I'm not yet sure which additional language specific guides will come next.

**Comment by Isaac444** [comment]
Guides for Healthcare IT, Cyber Security, and Ethical Hacking? I plan to work in Healthcare, after I finish my studies. Knowledge of these topics will help me have a competitive edge.

**Comment by P1xt** [comment]
@Isaac444 I literally cannot write guides for HealthCare IT. I've done a lot of work in healthcare IT and every last bit of it required non-disclosures. I would have to walk too narrow a line between what is common knowledge, and what I might have learned in industry. In addition to my general stance on respecting intellectual property and not violating NDAs - there's also the fact that neither do I want to be sued by a multi-billion dollar corporation, or tossed in jail for accidentally open sourcing something I once learned while working on HIPAA protected data or while under security clearance. A guide on HealthCare IT will never, ever, be written by me. That said, the CS-WD guide would be an excellent start.

The CS-WD guide would likely be a pre-requisite to any Cyber Security or Ethical Hacking guide I put together as well. Let me know when you're close to finishing it and I'll start considering the "what next" guides.

**Comment by muubar** [comment]
i just finished the "create your own html/css template" project which means i finally finished tier 1 of WD-CS, but where can i host my template?, it has 4 html pages and surge.sh won't let me host multi-page project.

**Comment by P1xt** [comment]
@muubar What makes you think surge won't let you host a project with multiple html pages?

I just made a bare bones example, with four pages (index.html, blog.html, contact.html, and about.html) and deployed it to surge using the same normal command I'd use (surge from the command line) and it not only pulled up index, but also all the other pages. http://mellow-giraffe.surge.sh/

**Comment by Isaac444** [comment]
@P1xt 

Definitely don't want to get you sued. 

Business guide(the business of "development"??? I know openstax has some economics books. 
For future guides, if you are ever lost just give people more guides for in demand, hard to find skills/languages . :D

**Comment by P1xt** [comment]
@Isaac444 The thing is, most of that is all stuff that would come after wd-cs. I'm really hesitant to put out guides that require significant experience already with software engineering because of the potential for people thinking "damn YDKJS is hard, I'm just gonna do X instead" and then jump to X completely ignoring the fact that X guide depends on them having all the fundamentals down first.

**Comment by P1xt** [comment]
@Isaac444 there is zero chance that I do guides on business - because the prospect of having to preview a bunch of business courses and econ books sounds like pure torture to me. I teach people how to program. I will NOT be branching into anything that requires me to read one paragraph of an econ textbook - that'd be the pinnacle of boring.

**Comment by P1xt** [comment]
I'm shutting this thread down. It's getting quite long and I've already got plenty of plans for new guides that'll take me at least the next 6 months to implement.

**Comment by akherranz** [comment]
A guide to IOS development would be really appreciated. Thanks for the guides P1xt

**Comment by P1xt** [comment]
@akherranz IOS development guide won't be coming until such time as Apple doesn't tie deploying to the app store to the purchase of Apple hardware - I try to steer clear of guides that don't have a clear path for those with low funds, or at least put them off until the very last.

**Comment by Isaac444** [comment]
cryptocurrency guide?

**Comment by P1xt** [comment]
I will not be adding any cryptocurrency or blockchain guides. Ever. I would fear that far too often, people would skip to the end-game without learning basics thinking "let me get in on this get rich quick scheme", learn far too little, do a crap job of it, and lose time and money they can ill afford.

**Comment by P1xt** [comment]
And, then blame me :smile:

**Comment by P1xt** [comment]
@Isaac444 finish the CS-WD guide and you'll be well prepared to investigate cryptocurrencies and blockchain on your own.

**Comment by AnaRobynn** [comment]
@P1xt I agree. Cryptocurrency and blockchain is not something you want to quickly learn, just because it seems lucrative, because it will slam you in the face hard.

**Comment by Isaac444** [comment]
self driving car guide?

**Comment by P1xt** [comment]
@Isaac444 Hit me up once you've finished the CS-WD and Data Science guides :smile:

**Comment by Curi-ous** [comment]
Hello,
any news on the Testing Web Application guide and what do you recommend me to do while waiting for it?

**Comment by P1xt** [comment]
@Curi-ous Which guide are you working on, and how far into it are you?

**Comment by Curi-ous** [comment]
Haven't started anyone yet

**Comment by P1xt** [comment]
@Curi-ous When you pick one, and complete it, let me know and I'll be sure to get you a set of supplementary resources for testing that complement that particular guide.

**Comment by shivendrarox** [comment]
An IOT guide using raspberry pi?

**Comment by rna7** [comment]
Salesforce Architect Developer guides?

AWS guides?

**Comment by desmondpsingh** [comment]
Have any guides been created yet?
