### ISSUE TITLE
Biology textbook returns 404

### ISSUE THREAD

**Issue by stephenjfox** [P1xt/p1xt-guides#32]
The text titled simply "Biology" - www.openstax.org/details/books/biology - returns 404.
This may be temporary (OpenStax having issues), but if not the content will need replacing.

**Comment by P1xt** [comment]
It does appear that openstax is having some issues right now.

**Comment by P1xt** [comment]
For the biology text you can get it here: https://cnx.org/contents/GFy_h8cu@10.118:rZudN6XP@2/Introduction

For any of the others, you can find them all here:
https://cnx.org/

**Comment by P1xt** [comment]
I'll double check in a couple days to see if they've resolved their DNS issue, and if they haven't, make a sweep through the guides and switch everything to cnx.org links.

**Comment by P1xt** [comment]
It appears openstax fixed their dns issue so I'm going to close this out.

Thanks for the heads up so I knew to watch for it @stephenjfox
