### ISSUE TITLE
Free alternative for 'Build Interactive JavaScript Charts with D3 V4' course

### ISSUE THREAD

**Issue by vibhor-kainth** [P1xt/p1xt-guides#34]
Hey @P1xt was the course [Build Interactive JavaScript Charts with D3 V4](https://egghead.io/courses/build-interactive-javascript-charts-with-d3-v4) free or did it always require a Pro subscription? This Udacity course [Data Visualization and D3js](https://www.udacity.com/course/data-visualization-and-d3js--ud507) could be a viable alternative.

**Comment by P1xt** [comment]
Drat, yes it was free when I added it, I'll take a look around for other alternatives then add the one you linked unless I find a better option that doesn't require a subscription.

**Comment by P1xt** [comment]
@vibhor-kainth (or anyone else interested) - I didn't find another free resource comparable to the Udacity one. If you'd like, go ahead and open a pull request to swap  [Build Interactive JavaScript Charts with D3 V4](https://egghead.io/courses/build-interactive-javascript-charts-with-d3-v4) for [Data Visualization and D3js](https://www.udacity.com/course/data-visualization-and-d3js--ud507). If no one wants the PR, I'll swap it out myself over the weekend.

**Comment by vibhor-kainth** [comment]
@P1xt I'll be happy to make the pull request. I just need some guidance as this will be my first ever pull request.

**Comment by P1xt** [comment]
@vibhor-kainth fork the repo, edit the markdown files to change everything to point to the new course.

Then pop into your fork on githun, click the "pull requests" tab, and click the "open a pull request" link.

If you need a more detailed walkthrough, @kornil's articles (which I link to in the FAQ) are truly fantastic.

**Comment by P1xt** [comment]
closed by 42e0a937086c9d346a721683d864b9f4980c0aa9
