### ISSUE TITLE
Can you also add time-frame need to complete each guide?

### ISSUE THREAD

**Issue by vaibhavmule** [P1xt/p1xt-guides#40]
I know it is self-paced, but feel better if there is estimated time frame?

**Comment by P1xt** [comment]
Sorry, but no I will never add that. There is no way to accurately estimate in a way that's meaningful for any particular individual. You will have to begin studying and then gauge what is a reasonable time-frame for you. I have no way of knowing how many hours per day you plan to study, whether you "study hard" or are "playing Halo and sorta watching the videos on the side". I don't know whether you jump to youtube or udemy looking for something easier whenever something gets difficult. I don't know anything about you, so I can't predict how long it will take you to complete something. You know you though - which makes you the perfect person to decide how long something will take for you

If I tag everything with "it'll take this long", immediately 98% of the people working through the guide will be thinking "I finished that way faster" or "that took me a lot longer" - some people are faster at one part, but struggle more with another, it's self paced so some people set aside 8 hours uninterrupted per day and really focus, while others have two kids and a job and are lucky to get a few hours per week before bed.

I try always to only add things that have meaning to the guides - if I added time-frames, they'd have no meaning, it would just be me tacking arbitrary numbers onto things to give people "warm and fuzzy" feelings. I've said it from day one: I'm not going to do it, start working through the guides and once you have a feel for how quickly you progress at the pace you set for yourself, make your own time estimates that are optimized for you.

**Comment by vaibhavmule** [comment]
I get your point and agree with you.

Thanks for insight on this.

On 27 Oct 2017 8:06 p.m., "P1xt" <notifications@github.com> wrote:

Sorry, but no I will never add that. There is no way to accurately estimate
in a way that's meaningful for any particular individual. You will have to
begin studying and then gauge what is a reasonable time-frame for you. I
have no way of knowing how many hours per day you plan to study, whether
you "study hard" or are "playing Halo and sorta watching the videos on the
side". I don't know whether you jump to youtube or udemy looking for
something easier whenever something gets difficult. I don't know anything
about you, so I can't predict how long it will take you to complete
something. You know you though - which makes you the perfect person to
decide how long something will take for you

If I tag everything with "it'll take this long", immediately 98% of the
people working through the guide will be thinking "I finished that way
faster" or "that took me a lot longer" - some people are faster at one
part, but struggle more with another, it's self paced so some people set
aside 8 hours uninterrupted per day and really focus, while others have two
kids and a job and are lucky to get a few hours per week before bed.

I try always to only add things that have meaning to the guides - if I
added time-frames, they'd have no meaning, it would just be me tacking
arbitrary numbers onto things to give people "warm and fuzzy" feelings.
I've said it from day one: I'm not going to do it, start working through
the guides and once you have a feel for how quickly you progress at the
pace you set for yourself, make your own time estimates that are optimized
for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/P1xt/p1xt-guides/issues/40#issuecomment-339989709>, or mute
the thread
