### ISSUE TITLE
Re-introduce Javascript Spessore

### ISSUE THREAD

**Issue by stephenjfox** [P1xt/p1xt-guides#41]
The [author has the books on his GitHub account](https://github.com/raganwald/javascript-spessore) so it can return as the preference over Eric Elliott's Programming JS Applications

**Comment by P1xt** [comment]
I considered that, but what's on his github account isn't in any state to be read comfortably. I won't be swapping it back in unless he re-releases it in a readable format.

**Comment by jasonsbarr** [comment]
He does have a [PDF version](https://github.com/raganwald/javascript-spessore/blob/master/published/javascript-spessore.pdf) also in his GitHub account, though I don't know if it's the final version as it was available on LeanPub or not.

For the record, though, Elliott's book is excellent.

**Comment by P1xt** [comment]
I think, of the two, I'd rather stick with Elliott's, it adds a bit more of a broad overview than Spessore.
