### ISSUE TITLE
"A Self-Learning, Modern Computer Science Curriculum"

### ISSUE THREAD

**Issue by Isaac444** [P1xt/p1xt-guides#42]
Found this guide that is suppose to give people the knowledge of a senior CMU computer science student. Check out this guide and see if there is anything you can implement, in your own guides.

https://functionalcs.github.io/curriculum/

"The goal of this guide is to build up to a senior undergrad level in computer science with the necessary rigorous background in fundamentals to understand academic papers in journals to continue self-learning"

**Comment by P1xt** [comment]
Thank you, but I already have the rigorous cs coverage I want in the CS guide and to a lesser extent in the guides that lean more heavily on web development.
