### ISSUE TITLE
unity for video game programming

### ISSUE THREAD

**Issue by jajcelol1** [P1xt/p1xt-guides#53]
what can i do if i want to learn unity and c# (because unity uses it) for game programming should i do all the parts that have math and game development theory  and replace the parts c++ courses with c# courses?

**Comment by P1xt** [comment]
In Tier 4, replace the UE4 specifics:

>  Getting Started Get Started with UE4
>  Tutorials: Unreal Engine 4 official video tutorials
>  Documentation: Unreal Engine 4 Documentation

with a couple C# courses and a thorough review of the Unity docs and tutorials. I'd leave everything else the same. Yes, even the C++ stuff earlier - there's better content for C++, so just use it, all of the concepts will translate over when you pick up C#.

**Comment by jajcelol1** [comment]
ok thank you for the advice
