### ISSUE TITLE
OSU Calculus courses on Coursera are being decommissioned

### ISSUE THREAD

**Issue by P1xt** [P1xt/p1xt-guides#57]
Note to self: 

The last offerings of OSU's calculus courses on Coursera are being decommissioned in May, 2018.

Either swap them out for MITOCW versions, or for the OSU "Ximera" project at that point.

**Comment by stephenjfox** [comment]
Based on my investigations into Ximera

OSU's Calculus 1 seems to map nicely to [Ximera's Calculus 1](https://ximera.osu.edu/mooculus/calculus1)

To cover the same content as OSU's Calculus 2 "Series and Sequences", you would need both:

- Ximera [Calculus 2](https://ximera.osu.edu/mooculus/calculus2)
- Ximera [Calculus A2](https://ximera.osu.edu/mooculus/calculusA2)

How well do you think that plurality of content with play with the spirit of the guides?

**Comment by P1xt** [comment]
It's the knowledge that matters, not where it comes from - Right now it's a tossup between Ximera and MITOCW. I'm leaning towards MITOCW though.

**Comment by rijavecb** [comment]
[Mooculus](https://mooculus.osu.edu) should have exactly the same content as what is up on Coursera, I had it bookmarked for a while but not sure where I found it.

**Comment by XavierR1985** [comment]
On OSSU, this is [the alternative link](https://mooculus.osu.edu/). What do you guys think?

**Comment by P1xt** [comment]
Switched to MITOCW for calculus courses.
