### ISSUE TITLE
job-ready.md backend cert

### ISSUE THREAD

**Issue by jkilgore07** [P1xt/p1xt-guides#67]
Hey P1xt. Thanks for all the work you put into these guides. I have noticed that there is no longer a backend certification under the freecodecamp curriculum. Could you please advise what projects to do instead. Have they just been renamed and shuffled around in the FCC curriculum? Or are those projects no longer available? I want to get a job as a junior web developer and work on games in my free time. Is the javascript 2.0 where I want to start? Thanks again for everything you do!

**Comment by P1xt** [comment]
How far into the guide are you? (Have you finished everything before the "backend cert" projects? If so, I'll light a fire under my "replace the FCC projects" effort.)

**Comment by jkilgore07** [comment]
I'm on the YDKJS Async & performance. Should I start a new issue when im a few steps from the backend?

**Comment by jkilgore07** [comment]
Awesome! Thanks again for all you do.

**Comment by miku86** [comment]
Does Backend Cert mean:
- Apis And Microservices Certification (300 hours) and
- Information Security And Quality Assurance Certification (300 hours)
?

**Comment by NikAHernandez** [comment]
@miku86 

I believe that before they launched their new curriculum, FreeCodeCamp had three different certifications, one of which was broadly labeled as Backend Cert. 

However, they now replaced those certs with about 5 other certifications, and the two that you are referring to are supposed to replace the old backend certification (I think). I'm not sure how well they cover backend information compared to what was previously up on the curriculum. 

I do think that @P1xt is looking to replace that step in the guide, but I'm not 100% sure.

**Comment by P1xt** [comment]
I'm actually thinking it's time for another revamp of the job ready guide (don't worry, YDKJS and CS50 will still be in the new version) - in the meantime, just assume the Backend projects are the ones from:

Apis And Microservices Certification (300 hours) and
Information Security And Quality Assurance Certification (300 hours)

**Comment by P1xt** [comment]
The revamp is finished and is now linked from the main page or you can find it here: 

[Job Ready Guide - JavaScript Edition 3.0](https://github.com/P1xt/p1xt-guides/blob/master/job-ready-javascript-edition-3.0.md)
