### ISSUE TITLE
Advice 

### ISSUE THREAD

**Issue by lucasmendev** [P1xt/p1xt-guides#71]
Hello P1xt, 
I am sending this message in order to receive some information about your guides (despite I had already read all the informations about them) and some advice about my career (if possibly). 
To begin with, I don’t have a Computer Science background. In fact, I was Lawyer and I decided to change my career, indeed. I have been studying a lot of “stuffs” (HTML, CSS, JavaScript) for 5 months. Additionally, I have been focusing on the “front-end” area. In September, I will begin my college related with UX Design (I needed to apply for a college program in order to enhance the possibility to immigrate). Despite of this, I want to link the knowledge I will absorb in my college program with “devolpement” skills. This statement can illustrate that I really want to work as a “developer” and using the UX Design skills as supporter or differential. Moreover, despite of the aforementioned knowledge in “development”, I can’t see myself working just as a “Front-End” developer. I would like construct different and valuable “things”, using innovation and technology, and not just to focus in web development. On the other hand, I think Machine Learning and AI could be suitable for all my desire (as I mentioned above) and perspective future (I am not completely sure about that). I am not sure whether I was clear or not but I am trying to look to the future and thriving to begin my studies (and career) associated with what I want to do in the future. 
I hope you can help and advice me about which should I do at this moment and which type of guide could I follow and study it deeply. 
Sorry about any mistakes on my writing. I am learning English. 
Best wishes,

**Comment by P1xt** [comment]
@lucasmendev do this one, it will prepare you most thoroughly to be a versatile and competent developer:

https://github.com/P1xt/p1xt-guides/blob/master/cs-wd.md

**Comment by lucasmendev** [comment]
Thanks P1tx for your attention and support. 
After the CSWD guide, would you suggest another guide made by you as a consequence of the improvement throughout your first guide? 
I am asking this just for don’t ask again the same question in the future. Thanks!

**Comment by lucasmendev** [comment]
Thank you very much!
