### ISSUE TITLE
Any free alternative to Java programming basics course on Udacity?

### ISSUE THREAD

**Issue by debu2code** [P1xt/p1xt-guides#72]
Hi P1xt!  I'm learning to code all by myself by reading through your guides. Thanks a lot for making this guides available.

Currently, I'm going through your guide on native android development. However, the Java basics course on Udacity is not free. Can you please provide any free resource on Java that can replace this Udacity course?

**Comment by Neous1** [comment]
is this the course you're referring to? https://www.udacity.com/course/java-programming-basics--ud282
if so, it is indeed free.

**Comment by debu2code** [comment]
But it's not free when I visit the link!! See here -
![java-udacity](https://user-images.githubusercontent.com/26302604/42409929-226f119c-81ff-11e8-9665-fb702ab494c3.jpg)

**Comment by Neous1** [comment]
I see what you mean, my link is redirected on your end to a java foundation nanodegree.
just for curiosity sake, do you have an option of free courses?

**Comment by debu2code** [comment]
@Neous1 The Udacity Java course is free in the US market. But they have made it paid one in India, I think.

Anyway, actually there're several YT channels but I just want to see if @P1xt has any recommendation...

**Comment by P1xt** [comment]
I'd give https://www.edx.org/course/java-fundamentals-for-android-development a try.

Or, just jump straight into the official Java Tutorials, they're quite good: https://docs.oracle.com/javase/tutorial/

**Comment by debu2code** [comment]
Thanks @P1xt! I've already started with the official Java tutorials. As you say, they're really good.

I'll also checkout the EdX course.

**Comment by debu2code** [comment]
Thanks @P1xt! I've already started with the official Java tutorials. As you say, they're really good.

I'll also checkout the EdX course.
