### ISSUE TITLE
[game-programming] reference no longer available: http://www.aaroncox.net/tutorials/arcade

### ISSUE THREAD

**Issue by ksmai** [P1xt/p1xt-guides#74]
Items affected:

[Tier 1]
Article: 2D Tutorial Series Introduction
Game: Pong (Reference Tutorial Paddle Battle)

[Tier 2]
Game: Tetris (Reference tutorial Falling Blocks (Tetris))
Game: Breakout (Reference tutorial Block Breaker (Breakout))

**Comment by P1xt** [comment]
Updated game programming guide to 2.0 version which cleans up broken links, adds CS50's game programming course, and adds some additional practice.

The new version may be found [here](https://github.com/P1xt/p1xt-guides/blob/master/game-programming-2.0.md)
