### ISSUE TITLE
Blockchain and/or Ethereum guide?

### ISSUE THREAD

**Issue by Ryan-ED** [P1xt/p1xt-guides#75]
First off, I love this repo. These guides are so helpful and I am shameless in recommending them to friends or family who want to start any kind of programming.

However, the other day a friend of mine asked about blockchain and Ethereum development and I was completely clueless on the topic. Considering the popularity of cryptocurrencies, would such a guide be possible?

Thanks. Much love.

**Comment by P1xt** [comment]
I've thought about this a good long while and I'm going to stick with the answer I gave last year on this - which is, basically 'No'. More specifically, I really feel that there's risks to fiddling with cryptocurrencies (especially for devs just starting out) and I don't want to be the one giving people just enough ammo to shoot off their own foot.

**Comment by P1xt** [comment]
Here's what I wrote last year concerning it (and yep, I'm sticking with this answer):

> I will not be adding any cryptocurrency or blockchain guides. Ever. I would fear that far too often, people would skip to the end-game without learning basics thinking "let me get in on this get rich quick scheme", learn far too little, do a crap job of it, and lose time and money they can ill afford.
