### ISSUE TITLE
M101P: MongoDB for Developers - Retired

### ISSUE THREAD

**Issue by erolaliyev** [P1xt/p1xt-guides#79]
On MongoDB University it has been written that this course has been retired and replaced by M220P: MongoDB for Python Developers. Should I take the new course or will you replace M101P: MongoDB for Developers with some other course?

**Comment by P1xt** [comment]
That's the course to go with, I've updated the guides to reflect it. Thank you for the heads up about the retired course!

850b7f4a17e8b041fa01ef74d2e4011392c2d0f6
d3f856a188e6fddd50b4e30b2f0491b0a0f160e8
