### ISSUE TITLE
Project alternatives to Netflix and Spotify

### ISSUE THREAD

**Issue by mamptecnocrata** [P1xt/p1xt-guides#8]
I felt very encouraged to carry out the projects, however, where I live there is no option to try to perform clones of Netflix or Spotify, since the records are not enabled for my country. Any other options available? And I already reviewed the FAQ and no one else has raised this doubt.

**Comment by P1xt** [comment]
Hmmm, I actually added Spotify for some without access to Netflix. I'll think about other alternatives. 

Question: is there an API that lists movies, including descriptions and images that IS available in your country?

**Comment by buoyantair** [comment]
Yeah, Spotify is not there in India as well. Sound could or Pandora would be nice

**Comment by P1xt** [comment]
Go ahead and use Pandora then and make it a sound rather than video app :D

**Comment by P1xt** [comment]
I've addressed this issue in the 2.0 version of the guide by specifying additional alternatives. Should anyone need an alternative for the Netflix/Spotify for the original guide, feel free to substitute Facebook, Twitter, Slack, Reddit or Medium.
