### ISSUE TITLE
Dead article link in CS - WD guide

### ISSUE THREAD

**Issue by jonah713** [P1xt/p1xt-guides#83]
Project Specification Documents:
http://www.pixelearth.net/pages/project-specification

**Comment by micmcgrorty** [comment]
This link is also dead for me.

**Comment by P1xt** [comment]
The site must have been down for a day, when I go there now I still see the page as it always was.

**Comment by P1xt** [comment]
Closing this for now, please re-open if you see the issue again and I'll swap that link for a backup off the wayback machine.
