### ISSUE TITLE
MOOC Java instead of CS106A?

### ISSUE THREAD

**Issue by ivantrj** [P1xt/p1xt-guides#86]
Hi p1xt, I am doing your Native Android guide and I am supposed to do Stanford's CS106A next, but I stumbled upon some reviews online saying that it might be better to do [this](http://moocfi.github.io/courses/2013/programming-part-1/material.html) instead of CS106A, because it is newer and teaches more. What do you think about this? Should I go for MOOC or stick with Stanford's course? 

Thank you for making these awesome guides.

**Comment by P1xt** [comment]
My recommendation remains CS106A. It teaches precisely what I need at that point in the guide to support what comes later in the guide.
