### ISSUE TITLE
CS-Java gap?

### ISSUE THREAD

**Issue by rna7** [P1xt/p1xt-guides#87]
Isn't there a big gap between  the following two steps?
Course: Introduction to Computer Science - CS50
Project: Google Code Jam 2008 - Qualification Round (language of your choice)

Or is this path meant to be followed after Javascript 3.0? Thanks

**Comment by P1xt** [comment]
There's no gap at all - you just finished CS50, where you learned the basics of both C and Python, and also some JavaScript, which gives you three languages you could leverage for the problems in the 2008 qualification round.

**Comment by rna7** [comment]
Okay I see. I guess I just need to slow down when solving code jam challenges. Thanks

**Comment by LShun** [comment]
@P1xt Hi, I don't feel like this question warrants a new issue. I'm having the same problem as @rna7 on this. For the first question, I spent 4 hours (used Pomodoro technique to keep track) but still unable to solve even the small one. Is it supposed to take this long or am I lacking in somewhere and need something to supplement? 

Also, is it recommended to look at the output solution when solving the problems? I'm thinking that will help immensely on figuring out the underlying algorithm, but might defeat the purpose of solving these questions.

**Comment by P1xt** [comment]
You've completely finished CS50?

**Comment by LShun** [comment]
@P1xt Yes, finished it.

**Comment by P1xt** [comment]
Then, if it takes you more than 20 hours total to do the code jam, table it and keep it in the wings to revisit periodically. Take long enough that you've given it a legit effort. But, don't halt your progress entirely for it - you will learn more every step of the way. No shame in circling back.

**Comment by LShun** [comment]
@P1xt Alright, thanks a lot!
