### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by rna7** [P1xt/p1xt-guides#89]
Is there a place for functional programming course in your CS guide? I've found the following which uses Haskell. https://www.edx.org/course/introduction-functional-programming-delftx-fp101x-0

The reason I'm asking is that Oxford University have Functional Programming early on in the first year.

https://www.cs.ox.ac.uk/admissions/undergraduate/courses/computer_science_core_1.html

https://www.cs.ox.ac.uk/admissions/undergraduate/courses/computer_science.html

http://www.cs.ox.ac.uk/files/8606/CourseStructure2018.pdf 

Thanks

**Comment by SharpEleven91** [comment]
I agree that it would be cool to see some more functional programming in the CS guide.

My recommendation would be https://www.coursera.org/learn/programming-languages. This course was just as impactful as the HTC series from UBC.

**Comment by P1xt** [comment]
@SharpEleven91 Adding more functional programming is definitely something I'm looking into for version 2 of the longer guides. I'm not sure I'd go with a coursera course though as their revenue model really breaks with the 'you can take it, and fully benefit from it' free philosophy I try to stick with in the guides. On some courses (like Sedgewik's Algorithms ones), the full course is available, but the majority of Coursera has projects and exams behind a pay wall now. There are several courses on mitocw that are quite awesome though, and it's likely they'll make an appearance. I need to think on it more though as I'm as yet undecided whether to go the Scheme/Lisp, Haskell, or Elixir route.

**Comment by P1xt** [comment]
@rna7 Please refrain from any further suggestions about what you think I should add to the guides until you have actually followed and finished one. It isn't my intention to be mean, but in all the time the past couple weeks you've spent researching what to learn and suggesting guide revisions, you could have been, well, actually learning. There are, of course, modifications I'll be making for the 2.0 versions of the longer guides. I already a virtual smorgasbord of ideas, alternatives, and 'this would be interesting's I've worked up on my own, plus I have a variety of contacts among people actually working through one of the guides who give me feedback and brainstorm ideas about interesting directions I could take the guides. If you are actually progressing through a guide, or, better yet, finishing a guide, you're in a much better position to give valuable feedback about additional content that would be helpful.

**Comment by rna7** [comment]
@p1xt that is fair enough. Thanks
