### ISSUE TITLE
edX paywall blocking access to resources

### ISSUE THREAD

**Issue by LShun** [P1xt/p1xt-guides#90]
Just started on How to Code: Simple Data and noticed edX implemented a new paywall system that blocks all graded assignments and limits access to course to around 21 days. Is there any plannings on creating alternatives to the courses on edX?

**Comment by SharpEleven91** [comment]
When the changes to edX were announced I didn't think it was going to be as bad as it is. But if P1xt plans on updating the guides for different resources I'd be more than willing to help look for them. 

Also, at this point I think coursera would be a better option over the edx classes. Most of the classes don't have a paywall, atleast the ones that I've taken.

**Comment by LShun** [comment]
Yea feels like I'm missing out a ton unless I pay. Some other CS roadmaps like OSSU also utilizes edX, and they don't seem to have any plans on replacing them as far as I know, so I was wondering if they are still perfectly fine without all the graded assessments

**Comment by P1xt** [comment]
Coursera is actually far worse about paywalls than edX. On their paywalled courses, there is no access to assessments at all (from day one) without paying.

I will look for replacements for the edx paywalled courses - though they are going to be quite difficult to find replacements for (the How to Code series is brilliant).

My recommendation in the meantime is to take your 21 day restriction as a challenge to finish within 21 days.

**Comment by P1xt** [comment]
Actually, I've had a 2.0 version in the works for some time now. It may be time to put the finishing touches on it and publish soon.

If you want a preview - this is its current (still needs editing and review) state:

**Comment by SharpEleven91** [comment]
Awesome! I'm most upset about the How to Code courses. Those were invaluable in my journey through the guides, they introduced me to functional programming. I would love to go back to those, but it's ridiculous that the testing and even some of the learning material is behind a paywall now.

**Comment by P1xt** [comment]
The How to Code courses are the ones that troubled me the most as well. They really are fantastic courses. There are other options for getting to the same place though. I was expecting they'd go paywall eventually because edx was toying with it last year. I'd been planning a few more months of research, but might speed that up and release the revamped guide sooner rather than later, I just need to review it all and double check it against the old to ensure I've not omitted any major topics.

**Comment by LShun** [comment]
Looks like I missed out some hot stuff then. But the new guide is awesome, looks like it solves the paywall issues. As an aside, it also seems much more approachable than the original one (example, the Code Jam 2008's "Fly swatter"). I'll close this issue once the new guide is up officially.

**Comment by garymdurante** [comment]
I have several questions, I hope its ok.

1. Why the Princeton Algorithms p1&2 were removed from the new guide?
2. Version 2.0 for python and android guides?
3. Why mooc.fi(java) p1&2 is not included in your guides?
4. What do you think of the free App Academy Open?

**Comment by garymdurante** [comment]
By the way, the new CSWD guide is awesome and I really like it and wanted to do it because I don't want to be just in front end development, however I find it daunting to tackle... seems its aimed for people who has a lot of time to spare for several years...

I only have a few hours of spare time a day to do the guide (family and work), to estimate, by browsing the guide, it would probably take me 5 to 10 years to complete the new cswd guide. 

Seems I'm stuck with JS v3.0

**Comment by P1xt** [comment]
@garymdurante

**Comment by P1xt** [comment]
> Looks like I missed out some hot stuff then. But the new guide is awesome, looks like it solves the paywall issues. As an aside, it also seems much more approachable than the original one (example, the Code Jam 2008's "Fly swatter"). I'll close this issue once the new guide is up officially.

"Fly Swatter" did exactly what it was supposed to. It challenged you. Heck, it's a problem you still remember. Sometimes you have to tackle 'the hard stuff' to get good at tackling 'the hard stuff'.

**Comment by jmccarty10** [comment]
I'm (slowly) working my way through the Python guide right now, actually.

**Comment by P1xt** [comment]
@jmccarty10 Thanks for letting me know. Knowing who's using what helps me prioritize what to update first. I won't forget Python ;)

**Comment by rmcguire6** [comment]
I'm also slowly working my way through the Python guide. Appreciate 
your work. There's plenty of stuff out there about Javascript but good 
Python resources seem to be harder to find. Thank you.
Regina

**Comment by RyRyMc** [comment]
Well just to throw my two cents in, I'm working through the Data Science guide if it needs updating too.

**Comment by vibhor-kainth** [comment]
Piggybacking off this thread, I would like to add that the Safari Books links now require a subscription. Eg: [Modern Java EE Design Patterns](https://www.oreilly.com/library/view/modern-java-ee/9781492042266/)

You can read the first chapter but everything else is behind a paywall.

**Comment by rna7** [comment]
@p1xt 

Why not use htdp book which the how to code course is based on?
https://htdp.org/

Or Berkley lectures for SICP book?
https://archive.org/details/ucberkeley-webcast-PL3E89002AA9B9879E?sort=titleSorter

https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book.html

**Comment by P1xt** [comment]
@rna7 htdp book is a great idea.

I doubt I'll add Berkeley lectures though - they have quite a few good courses but are prone to taking them offline without really any notice.

**Comment by rna7** [comment]
@p1xt 
I meant the Brian Harvey's Berkley lectures for Stricture and Interpretation of Computer Programs (SICP). It is fully uploaded for 2015 version on the archive.org link in my previous comments. The course materials and lecture notes are fairly easy to find as well with a quick google search.

Regarding pay walled edX courses, I haven't experienced this yet, but have thought of taking a 'backup' of the videos and course materials.

For those that don't want to go down that route, the guy from How to Code series has a YouTube channel with older version of the same content.
I'm not sure how far into the material he goes though.

**Comment by rna7** [comment]
Here's link 
https://m.youtube.com/channel/UC7dEjIUwSxSNcW4PqNRQW8w/playlists

**Comment by shivendrarox** [comment]
I was just reading this thread, I am from india and here we have a MOOC provider which provides moocs and assignments(which have deadlines and are checked also) , it's powered by government so its free for everyone and anyone from any country can access it, it provides all courses in english language too.
https://nptel.ac.in/

**Comment by masterseeker** [comment]
@P1xt 
Hi just came across your awesome guides and was seeking some advice. I have already completed How to Automate the boring stuff, MIT 6.00.1X and CS50, and I'm halfway through 6.00.2X.  I'm currently most interested in the back end. But was wondering whether would it be beneficial to complete Python Guide then Move onto the CSBE java guide or start the CSBE guide straightaway. Also I Have completed the the first Course in Duke's Java series [here](https://www.coursera.org/specializations/object-oriented-programming) and wanted to know if these courses are any sort of replacement for the how to code series considering what has happened on edx. The java course i took over half the questions were graded and the ungraded questions were still visible.

**Comment by P1xt** [comment]
@shivendrarox I took a look through that site and it has an amazing bunch of resources. Unfortunately, many (most) I looked at just had video lectures, with no projects, quizzes, or problems to solve.

**Comment by P1xt** [comment]
@masterseeker were I in your position right now, I'd take a look at the work in progress revamped guide I posted here: https://github.com/P1xt/p1xt-guides/issues/90#issuecomment-471812536

... and, do Tier 1 for now - ensuring all your Tier projects involve backend development with Python.

**Comment by shivendrarox** [comment]
@p1xt nptel provides quizzes and assignments during a semester for duration ranging from 4 week to 12 weeks. After this time the course instructors close the assignments and quiz submission window. This is usually done near the semester end.
Since this semester is finished in nearly all of india, so you will not be able to see the assignments portal, but here i have a sheet for next semesters schedule for all the courses in the platform, during which the assignments window will be available

https://docs.google.com/spreadsheets/d/e/2PACX-1vRgBO0bXtb52Ocx-aT7yy6j5twA-3GcgWiN5RCGboG3XTD6P5hWpG_jbz8PZA1Aw5YPl2MeEPziCyKm/pubhtml?gid=0&single=true

**Comment by masterseeker** [comment]
@P1xt ok Thanks for the reply will do. Also in your math prep section on revamped guide you omitted Geometry is this not needed to prepare myself for calculus. Asking as I have nearly gone through the algebra 1 section and was about to start geometry

**Comment by P1xt** [comment]
@masterseeker geometry is awesome and fantastic to know - however, trig/algebra are far more pertinent at that point

**Comment by P1xt** [comment]
@masterseeker geometry is awesome and fantastic to know - however, trig/algebra are far more pertinent at that point

**Comment by P1xt** [comment]
Closed with https://github.com/P1xt/p1xt-guides/commit/4376d0252966a4718d1f9e77eba880038ec597d2 which revises the entire curriculum to focus on core topics and specializations with a strong selection of resources not likely to be paywalled.

**Comment by PERCE-NEIGE** [comment]
"Coursera is actually far worse about paywalls than edX. On their paywalled courses, there is no access to assessments at all (from day one) without paying."

It's exactly what Edx do now, and Coursera is now a far better option, because ALL Edx courses are now paywalled.

**Comment by P1xt** [comment]
That's not quite true @PERCE-NEIGE - There are still some courses that are completely not paywalled on both platforms. 

The Stanford Algorithms courses by Sedgewick on Coursera, and the Harvard CS50 courses on edX come immediately to mind.

It's so uncommon though, to find a non-paywalled course, on either platform that those courses I listed are really the exceptions that prove the rule.
