### ISSUE TITLE
Approaching GCJ & substituting with HackerRank medium problems

### ISSUE THREAD

**Issue by LShun** [P1xt/p1xt-guides#91]
Hi, this might not be a problem inherent to the guide of CS-Java itself but might be one plaguing new programmers like me, so I hope to get some input. 

TL;DR: Stuck on problems in GCJ 2008 & 2009, can't progress much without copy pasting (with understanding) or reading content analysis due to possibly arcane terms. Is this the guide's intention for us to google answers up? Also thinking of substituing GCJ problems with HackerRank mediums as a softer approach to learning problem-solving.

Basically when I was solving _Project: Google Code Jam 2008 - Qualification Round (language of 
your choice)_, 

1. I can't solve Saving the Universe and had to look up the analysis for hints, discovering the greedy algorithm (although it was mentioned briefly in CS50)
2. I managed to solve Timetable because it has the same pattern as Saving the Universe and it just jumps out at me.
3. I completely gave up on Fly Swatter, after around 20 hours of effort. My mind is lost at "Circular sectors". I tried drawing it out, trying to understand how to use them for different parts of the circle. I had to look up and copy other's solution to understand it.

This is pretty much my case on GCJ 2009 too. Basically, is it the guide's intention for us to google up some questions and/or look at the content analysis, or are we really supposed to hunker down and use dozens of hours (probably just me) to solve problems?

This is because some of the contests introduce new, pretty arcane terms for me like "dynamic programming" which I really never knew unless I look at the analysis. I think I could really spend hundreds of hours to solve it without looking it up. 

The alternative to table it and come back later doesn't work...as well? Because as you keep progressing you notice all your previous GCJ checkboxes are all unchecked. It's not demotivating just feels like lack of progress.

I'm also thinking of supplementing with HackerRank medium problems because they're easier one way or another. Sometimes, they introduce algorithms like DFS before sending us to the problems. I'd like to know is that a good substitute?

**Comment by P1xt** [comment]
I know this answer isn't the one you are hoping for. But, yes, the intention was for you to take dozens of hours to figure it out. And, if a single problem is still not solvable at that point, table it and come back when you know more.

You're probably thinking "what the actual hell, why would she do this to me"?

And, the answer that is actually in your question:

> I managed to solve Timetable because it has the same pattern as Saving the Universe and it just jumps out at me.

---
The more "big problems" you solve, not tiny little 5 minute checkmark and done busy work, but actual substantial problems that require multiple work sessions and a fair number of hours ... the more patterns to solving the "tough stuff" will just jump out at you.

If you are at 20 hours on a single problem and it seems there is no end in sight, table it. If it helps you from a "not being haunted by that unchecked box in your path", then just cut and paste the line for that one down into the next tier, make it be due then, not now.

**Comment by P1xt** [comment]
That said - rather than HackerRank, my recommendation would be to defer the GCJ if you're well and truly stuck and replace it (for now) with https://www.khanacademy.org/computing/computer-science/algorithms which is reasonably short to complete, but will give you an introduction that might lead to rather a lot more of those 'just jumps out at me' moments.

**Comment by LShun** [comment]
Alright, thanks for the clarification and recommendation! I was thinking if my working direction has strayed off course, but well, just gotta keep walking to see the light in the tunnel.

I'll start on KhanAcademy and close off the thread.
