### ISSUE TITLE
Replace items

### ISSUE THREAD

**Issue by astrakhanRinat** [P1xt/p1xt-guides#94]
Hello. Please replace "Course: Learn to Code HTML & CSS" and "Course: Learn to Code Advanced HTML & CSS" in guide "Ready for Job JS". There are a lot of mistakes in CodePen display examples. And why they are so bright?

**Comment by P1xt** [comment]
No
My preference for that part would be to include items which would have you thoroughly study the MDN documentation for HTML, CSS and JavaScript. However, that would be far more work, far more difficult, and be much more prone to learners deciding to skip the difficult parts.
