### ISSUE TITLE
Bootstrap and jQuery

### ISSUE THREAD

**Issue by astrakhanRinat** [P1xt/p1xt-guides#96]
Hello. Must I learn and use Bootstrap and jQuery? Must I use it when I will create projects based on your useful JS guide - Ready for Job? Thank you )

**Comment by P1xt** [comment]
You can use whatever you want to create the projects. You 'could' (but not must) use Bootstrap and jQuery. You could use vanilla JavaScript and plain CSS. You could decide to use React with Emotion or Angular with Sass. Think of it as a choose your own adventure - use what you want to learn well.
