### ISSUE TITLE
Fullstack Web Development guide just covers front end part

### ISSUE THREAD

**Issue by 805bluebell** [P1xt/p1xt-guides#98]
Full-stack Web Development guide at https://github.com/P1xt/p1xt-guides/blob/master/speedrun-practice/fullstack-dev.md just covers front end part.

I think it is a clone of "Frontend Web Development".
More stuff needs to be added for the backend.

**Comment by P1xt** [comment]
First - that link doesn't point to a guide, it points to a list of practice projects for fullstack development.

Second - what about creating a fullstack flash cards app, a fullstack project of your choice, cloning twitter, cloning medium, etc, isn't fullstack?
